package neu.edu.entity;
// Generated Apr 27, 2017 1:00:33 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserProject generated by hbm2java
 */
public class UserProject implements java.io.Serializable {

	private Integer projectid;
	private UserAccount userAccount;
	private String title;
	private String description;
	private Date enddate;
	private String category;
	private String status;
	private Float goal;
	private Integer count;
	private String shortdesc;
	private Integer liked;
	private Integer hate;
	private Float received;
	private String service1;
	private String service2;
	private String service3;
	private String amount1;
	private String amount2;
	private String amount3;
	private String cart;
	private Set<UserComment> userComments = new HashSet<UserComment>(0);
	private Set<PaymentInfo> paymentInfos = new HashSet<PaymentInfo>(0);

	public UserProject() {
	}

	public UserProject(UserAccount userAccount) {
		this.userAccount = userAccount;
	}

	public UserProject(UserAccount userAccount, String title, String description, Date enddate, String category,
			String status, Float goal, Integer count, String shortdesc, Integer liked, Integer hate, Float received,
			String service1, String service2, String service3, String amount1, String amount2, String amount3,
			String cart, Set<UserComment> userComments, Set<PaymentInfo> paymentInfos) {
		this.userAccount = userAccount;
		this.title = title;
		this.description = description;
		this.enddate = enddate;
		this.category = category;
		this.status = status;
		this.goal = goal;
		this.count = count;
		this.shortdesc = shortdesc;
		this.liked = liked;
		this.hate = hate;
		this.received = received;
		this.service1 = service1;
		this.service2 = service2;
		this.service3 = service3;
		this.amount1 = amount1;
		this.amount2 = amount2;
		this.amount3 = amount3;
		this.cart = cart;
		this.userComments = userComments;
		this.paymentInfos = paymentInfos;
	}

	public Integer getProjectid() {
		return this.projectid;
	}

	public void setProjectid(Integer projectid) {
		this.projectid = projectid;
	}

	public UserAccount getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(UserAccount userAccount) {
		this.userAccount = userAccount;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Float getGoal() {
		return this.goal;
	}

	public void setGoal(Float goal) {
		this.goal = goal;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public String getShortdesc() {
		return this.shortdesc;
	}

	public void setShortdesc(String shortdesc) {
		this.shortdesc = shortdesc;
	}

	public Integer getLiked() {
		return this.liked;
	}

	public void setLiked(Integer liked) {
		this.liked = liked;
	}

	public Integer getHate() {
		return this.hate;
	}

	public void setHate(Integer hate) {
		this.hate = hate;
	}

	public Float getReceived() {
		return this.received;
	}

	public void setReceived(Float received) {
		this.received = received;
	}

	public String getService1() {
		return this.service1;
	}

	public void setService1(String service1) {
		this.service1 = service1;
	}

	public String getService2() {
		return this.service2;
	}

	public void setService2(String service2) {
		this.service2 = service2;
	}

	public String getService3() {
		return this.service3;
	}

	public void setService3(String service3) {
		this.service3 = service3;
	}

	public String getAmount1() {
		return this.amount1;
	}

	public void setAmount1(String amount1) {
		this.amount1 = amount1;
	}

	public String getAmount2() {
		return this.amount2;
	}

	public void setAmount2(String amount2) {
		this.amount2 = amount2;
	}

	public String getAmount3() {
		return this.amount3;
	}

	public void setAmount3(String amount3) {
		this.amount3 = amount3;
	}

	public String getCart() {
		return this.cart;
	}

	public void setCart(String cart) {
		this.cart = cart;
	}

	public Set<UserComment> getUserComments() {
		return this.userComments;
	}

	public void setUserComments(Set<UserComment> userComments) {
		this.userComments = userComments;
	}

	public Set<PaymentInfo> getPaymentInfos() {
		return this.paymentInfos;
	}

	public void setPaymentInfos(Set<PaymentInfo> paymentInfos) {
		this.paymentInfos = paymentInfos;
	}

}
