package neu.edu.entity;
// Generated Apr 27, 2017 1:00:33 AM by Hibernate Tools 5.2.1.Final

/**
 * UserComment generated by hbm2java
 */
public class UserComment implements java.io.Serializable {

	private Integer commentid;
	private UserProject userProject;
	private String message;
	private String username;

	public UserComment() {
	}

	public UserComment(UserProject userProject, String message, String username) {
		this.userProject = userProject;
		this.message = message;
		this.username = username;
	}

	public Integer getCommentid() {
		return this.commentid;
	}

	public void setCommentid(Integer commentid) {
		this.commentid = commentid;
	}

	public UserProject getUserProject() {
		return this.userProject;
	}

	public void setUserProject(UserProject userProject) {
		this.userProject = userProject;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

}
