package neu.edu.entity;
// Generated Apr 27, 2017 1:00:33 AM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * UserAccount generated by hbm2java
 */
public class UserAccount implements java.io.Serializable {

	private Integer id;
	private String userName;
	private String firstname;
	private String password;
	private String role;
	private String lastname;
	private String email;
	private Set<PaymentInfo> paymentInfos = new HashSet<PaymentInfo>(0);
	private Set<UserProject> userProjects = new HashSet<UserProject>(0);

	public UserAccount() {
	}

	public UserAccount(String userName, String firstname, String password, String role, String lastname, String email,
			Set<PaymentInfo> paymentInfos, Set<UserProject> userProjects) {
		this.userName = userName;
		this.firstname = firstname;
		this.password = password;
		this.role = role;
		this.lastname = lastname;
		this.email = email;
		this.paymentInfos = paymentInfos;
		this.userProjects = userProjects;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set<PaymentInfo> getPaymentInfos() {
		return this.paymentInfos;
	}

	public void setPaymentInfos(Set<PaymentInfo> paymentInfos) {
		this.paymentInfos = paymentInfos;
	}

	public Set<UserProject> getUserProjects() {
		return this.userProjects;
	}

	public void setUserProjects(Set<UserProject> userProjects) {
		this.userProjects = userProjects;
	}

}
