package neu.edu.controller.output;
// Generated Apr 21, 2017 7:12:53 PM by Hibernate Tools 5.2.1.Final

/**
 * Category generated by hbm2java
 */
public class CategoryBeanOutput implements java.io.Serializable {

	private Integer categoryid;
	private String categoryname;

	public CategoryBeanOutput() {
	}

	public CategoryBeanOutput(String categoryname) {
		this.categoryname = categoryname;
	}

	public Integer getCategoryid() {
		return this.categoryid;
	}

	public void setCategoryid(Integer categoryid) {
		this.categoryid = categoryid;
	}

	public String getCategoryname() {
		return this.categoryname;
	}

	public void setCategoryname(String categoryname) {
		this.categoryname = categoryname;
	}

}
